### ISSUE TITLE
Question about AUs matrix

### ISSUE THREAD

**Issue by Shuaiyicao** [yalesong/BGCS#1]
In run_demo.m has a matrix AUs contains 24 labels.
```
AUs=[1,2,4,5,6,7,9,10,11,12,14,15,16,17,18,20,22,23,24,25,26,27,43,45];

trnLblMat{i} = trnLblMat{i}(:,AUs);
valLblMat{i} = valLblMat{i}(:,AUs);
tstLblMat{i} = tstLblMat{i}(:,AUs);
```
But if I want to use all of 100 labels, F1 = 0.
```
AUs = 1:1:100;
```
```
Experiment with [bcs]
Performance metric: f1
[BCS] 0.000000 (0.000000)
Performance metric: acc
[BCS] 0.962833 (0.000114)
```
I couldn't understand, maybe I make a mistake by using AUs.
I would greatly appreciate it if you would reply to me.

**Comment by yalesong** [comment]
What dataset are you using? How many AUs does your dataset have labels for? Does your dataset have at least one sample for each of the 100 AUs you wish to detect? By the way, I don't think there exists 100 AUs; check [codes for action units](https://en.wikipedia.org/wiki/Facial_Action_Coding_System#Codes_for_Action_Units).

**Comment by Shuaiyicao** [comment]
1. I am using the CK+ dataset.
2. I use BCS to classify text dataset, and I just want to know the result when I use all the labels.
3. I read the code again and I find something. When I use all of the labels,
```
AUs = 1:1:100;
```
struct R like this, and in get_best_results.m
```
R(k).pred.my.val>eval_thresh(l)
```
All of the elements in R(k).pred.my.val is zero.
But if I change a parameter in train_bcs.m
```
err<(1e-2) * 0.5
```
I can get a result seems right.
```
Experiment with [bcs]
Performance metric: f1
[BCS] 0.690943 (0.004074)
Performance metric: acc
[BCS] 0.978648 (0.000018)
```
But I think the acc is too high.

Maybe I don't get the key points in your paper and code.
Thank you for your reply and patience.

**Comment by yalesong** [comment]
I am confused as to what dataset you are using. What is the "text dataset" you are referring to? Are you using the CK+ to train your model, and your "text dataset" to test the trained model?

**Comment by Shuaiyicao** [comment]
Well, maybe I didn't express clearly.
I use CK+ dataset to train model and use CK+ dataset to test model. I just run the run_demo.m and want to know what result can I get.
And I get the correct result as you mention in run_demo.m.
```
%After running the script, you should get an output similar to following:
%   > Experiment with [bcs]
%   > Experiment with [bgcs]
%   > Performance metric: f1
%   > [BCS] 0.636313 (0.040117)
%   > [BGCS] 0.664994 (0.034730)
%   > Performance metric: acc
%   > [BCS] 0.901496 (0.002784)
%   > [BGCS] 0.906557 (0.002651)
```
But I came up with an idea, what result can I get with all of the AUs. I am curious about the differences between those two cases.
So I train model with 100 AUs, and test the model, however I get F1 = 0.
I know train model with 100 AUs is meaningless, and no practical purpose. But I am confused the reason which cause F1 = 0.

**Comment by yalesong** [comment]
Thanks for the clarification. The reason why you see F1=0 is that CK+ does not have samples for all 100 categories you wish to detect. Most importantly, as I mentioned above, there aren't 100 AUs defined. Please check [this page](https://en.wikipedia.org/wiki/Facial_Action_Coding_System#Codes_for_Action_Units) for valid AU categories.

Also, I would suggest checking the number of samples per AU in the CK+ dataset. (Sorry, I no longer have access to the dataset.)

**Comment by Shuaiyicao** [comment]
I check the CK+ dataset, actually, it doesn't have samples for all 100 categories.
Thank you very much!
